name: Pull Requests

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository
            ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install OpenJDK 11
        run: .ci/install-openjdk.sh 11
        shell: bash
      - name: Build
        run: .ci/build-pr.sh
        shell: bash
        env:
          PMD_CI_SECRET_PASSPHRASE: ${{ secrets.PMD_CI_SECRET_PASSPHRASE }}
          PMD_CI_BRANCH: ${{ github.ref }}
          PMD_CI_PULL_REQUEST_NUMBER: ${{ github.event.number }}
